# coding:utf-8

class Keycode(object):
    def __init__(self):
        super(Keycode, self).__init__()

    event_code_list = {
        # Keycode for phone
        'KEYCODE_CALL': 5,
        'KEYCODE_ENDCALL': 6,
        'KEYCODE_HOME': 3,
        'KEYCODE_MENU': 82,
        'KEYCODE_BACK': 4,
        'KEYCODE_SEARCH': 84,
        'KEYCODE_CAMERA': 27,
        'KEYCODE_FOCUS': 80,
        'KEYCODE_POWER': 26,
        'KEYCODE_NOTIFICATION': 83,
        'KEYCODE_VOLUME_MUTE': 164,
        'KEYCODE_VOLUME_UP': 24,
        'KEYCODE_VOLUME_DOWN': 25,
        # Keycode for control
        'KEYCODE_ENTER': 66,
        'KEYCODE_ESCAPE': 111,
        'KEYCODE_DPAD_CENTER': 23,
        'KEYCODE_DPAD_UP': 19,
        'KEYCODE_DPAD_DOWN': 20,
        'KEYCODE_DPAD_LEFT': 21,
        'KEYCODE_DPAD_RIGHT': 22,
        'KEYCODE_MOVE_HOME': 122,
        'KEYCODE_MOVE_END': 123,
        'KEYCODE_PAGE_UP': 92,
        'KEYCODE_PAGE_DOWN': 93,
        'KEYCODE_DEL': 67,
        'KEYCODE_FORWARD_DEL': 112,
        'KEYCODE_INSERT': 124,
        'KEYCODE_TAB': 61,
        'KEYCODE_NUM_LOCK': 143,
        'KEYCODE_CAPS_LOCK': 115,
        'KEYCODE_BREAK': 121,
        'KEYCODE_SCROLL_LOCK': 116,
        'KEYCODE_ZOOM_IN': 168,
        'KEYCODE_ZOOM_OUT': 169,
        # Keycode for basic
        'KEYCODE_0': 7,
        'KEYCODE_1': 8,
        'KEYCODE_2': 9,
        'KEYCODE_3': 10,
        'KEYCODE_4': 11,
        'KEYCODE_5': 12,
        'KEYCODE_6': 13,
        'KEYCODE_7': 14,
        'KEYCODE_8': 15,
        'KEYCODE_9': 16,
        'KEYCODE_A': 29,
        'KEYCODE_B': 30,
        'KEYCODE_C': 31,
        'KEYCODE_D': 32,
        'KEYCODE_E': 33,
        'KEYCODE_F': 34,
        'KEYCODE_G': 35,
        'KEYCODE_H': 36,
        'KEYCODE_I': 37,
        'KEYCODE_J': 38,
        'KEYCODE_K': 39,
        'KEYCODE_L': 40,
        'KEYCODE_M': 41,
        'KEYCODE_N': 42,
        'KEYCODE_O': 43,
        'KEYCODE_P': 44,
        'KEYCODE_Q': 45,
        'KEYCODE_R': 46,
        'KEYCODE_S': 47,
        'KEYCODE_T': 48,
        'KEYCODE_U': 49,
        'KEYCODE_V': 50,
        'KEYCODE_W': 51,
        'KEYCODE_X': 52,
        'KEYCODE_Y': 53,
        'KEYCODE_Z': 54,
        # Keycode for symbol
        'KEYCODE_PLUS': 3,
        'KEYCODE_MINUS': 3,
    }

    def get(self, keyname):
        return self.event_code_list[keyname]